services:
  - type: web
    name: acuvia-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python model/train.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHONIOENCODING
        value: utf-8
